AWSTemplateFormatVersion: 2010-09-09
Description: EC2 con Apache y página TTS en Español

Resources:
  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: us-east-1a
      ImageId: ami-0f88e80871fd81e91
      InstanceType: t3.micro
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          yum update -y
          yum install -y httpd -y
          systemctl start httpd
          systemctl enable httpd

          cat << 'EOF' > /var/www/html/index.html
          <!DOCTYPE html>
          <html lang="es">
          <head>
            <meta charset="utf-8" />
            <meta name="viewport" content="width=device-width,initial-scale=1" />
            <title>TTS Español — Generador de audio</title>
            <style>
              body {
                font-family: system-ui, -apple-system, "Segoe UI", Roboto, "Helvetica Neue", Arial;
                max-width: 760px;
                margin: 32px auto;
                padding: 18px;
                line-height: 1.45;
                color: #0f172a;
                background: #f8fafc;
              }
              h1 { color: #1e293b; }
              textarea {
                width: 100%;
                height: 130px;
                padding: 10px;
                border-radius: 8px;
                border: 1px solid #cbd5e1;
                resize: vertical;
              }
              button {
                padding: 10px 16px;
                background: #2563eb;
                border: none;
                color: white;
                border-radius: 8px;
                font-size: 15px;
                cursor: pointer;
              }
              button:hover { background: #1d4ed8; }
            </style>
          </head>

          <body>
            <h1>Generador de audio (TTS) en Español</h1>
            <p>Introduce texto y genera audio en español usando la API de OpenAI.</p>

            <textarea id="textInput" placeholder="Escribe el texto aquí..."></textarea>
            <br><br>

            <button onclick="generateAudio()">Generar Audio</button>

            <h2>Resultado:</h2>
            <audio id="audioPlayer" controls></audio>

            <script>
              async function generateAudio() {
                const text = document.getElementById("textInput").value;

                if (!text.trim()) {
                  alert("Por favor ingresa texto.");
                  return;
                }

                const response = await fetch("https://api.openai.com/v1/audio/speech", {
                  method: "POST",
                  headers: {
                    "Content-Type": "application/json",
                    "Authorization": "Bearer TU_API_KEY_AQUI"
                  },
                  body: JSON.stringify({
                    model: "gpt-4o-mini-tts",
                    voice: "alloy",
                    input: text
                  })
                });

                const arrayBuffer = await response.arrayBuffer();
                const audioBlob = new Blob([arrayBuffer], { type: "audio/mpeg" });
                const audioUrl = URL.createObjectURL(audioBlob);

                document.getElementById("audioPlayer").src = audioUrl;
              }
            </script>
          </body>
          </html>
          EOF
